app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="users/")

    def __str__(self):
        return self.name

app/forms.py
from django import forms

from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

app/views.py
from django.shortcuts import render

from .forms import UserForm
from .models import User


def home(request):
    context = dict()
    form = UserForm()
    if request.method =='POST' and request.FILES['photo']:
        form = UserForm(request.POST, request.FILES)

        if form.is_valid():
            user = form.save()

        return render(
            request, 'home.html',
            {
                'form': form,
                'user_photo_url': user.photo.url,
            },
        )

    return render(
        request, 'home.html',
        {
            'form': form,
        },
    )

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">

	<!-- TITLE -->
	<title>{% block title %}
		
	{% endblock title %}</title>
	
	<!-- STATIC CSS -->
	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{% static "css/style.css" %}">

	{% block stylesheet %}

	{% endblock stylesheet %}

</head>

<body>
	<main class="container">
		{% block content %}

		{% endblock content %}
	</main>
	
	<script src="{% static 'js/bootstrap.min.js' %}"></script> 
	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
	<script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

	{% block scripts %}

	{% endblock scripts %}
</body>
</html> 

templates/home.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% load static %}

{% block title %}
	Home page
{% endblock title %}

{% block content %}
<br>
<h1>Sử dụng Amazon S3 lưu trữ FILE STATIC/MEDIA</h1>


<form action=""  method="post" enctype="multipart/form-data" data-url="{% url "home" %}">
	{% csrf_token %}

	<div class="form-group">
		<label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
		{% render_field form.name class="form-control" %}
	</div>

	{% render_field form.photo class="form-control" style="display: none;" %}

	<div class="card" style="width: 18rem;">

		<img class="card-img-top" src="{{ user_photo_url }}">
		<div class="card-body">			
			<div id="js-upload" class="btn btn-danger"><i class="fa fa-camera upload-button"></i> Upload</div>
		</div>

	</div>
	<br>
	<button class="btn btn-primary">Save</button>
</form>

{% endblock content %}

{% block scripts %}
<script>
$(function(){

	var readURL = function(input) {
		if (input.files && input.files[0]) {
			var reader = new FileReader();
			reader.onload = function (e) {
				$('.card-img-top').attr('src', e.target.result);
			}
			reader.readAsDataURL(input.files[0]);
		}
	}


	$("#id_photo").on('change', function(){
		readURL(this);
	});

	$("#js-upload").on('click', function() {
		$("#id_photo").click();
	});

});

</script>
{% endblock scripts %}